import "./globals.css"
import type { Metadata } from "next"
import { Roboto, Poppins, Inter } from "next/font/google"
import localFont from "next/font/local"

import { cn } from "@/lib/utils"
import { QueryProvider } from "@/components/query-provider"
import { ThemeProvider } from "@/components/theme-provider"

const roboto = Roboto({
  variable: "--font-sans",
  subsets: ["latin"]
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

const ronzino = localFont({
  src: [
    {
      path: "../public/fonts/ronzino/ronzino-regular.otf",
      weight: "400",
      style: "normal"
    },
    {
      path: "../public/fonts/ronzino/ronzino-medium.otf",
      weight: "500",
      style: "normal"
    },
    {
      path: "../public/fonts/ronzino/ronzino-bold.otf",
      weight: "700",
      style: "normal"
    }
  ],
  variable: "--font-ronzino",
  display: "swap"
})

const sfCompact = localFont({
  src: [
    {
      path: "../public/fonts/sf-compact/sf-compact-regular.ttf",
      weight: "400",
      style: "normal"
    },
    {
      path: "../public/fonts/sf-compact/sf-compact-medium.ttf",
      weight: "500",
      style: "normal"
    },
    {
      path: "../public/fonts/sf-compact/sf-compact-bold.ttf",
      weight: "700",
      style: "normal"
    }
  ],
  variable: "--font-sf-compact",
  display: "swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          roboto.variable,
          ronzino.variable,
          poppins.variable,
          sfCompact.variable,
          inter.variable,
          "font-sans antialiased"
        )}
      >
        <ThemeProvider>
          <QueryProvider>{children}</QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
